### ISSUE TITLE
Can you pls clarify whether the results showing 0 to 100k images fed to generator are from flowers dataset? - Reg.,

### ISSUE THREAD

**Issue by JSP21** [dome272/ProjectedGAN-pytorch#2]
Hi,
Are the images shown to generator ranging from 0 to 100k from Oxford flowers dataset? If so, flowers dataset has around 8k images only. How 100k images are fed to generator? Kindly clarify!

Thanks.

**Comment by dome272** [comment]
Hey,
you are right that the Oxford Flowers Dataset only has about 9.000 images. By 100.000 images I simply mean the total numbe of images that were fed to the Generator. You can easily convert this into epoch notation by 100.000 / 9.000 which are about 11 epochs. I just used this notation, because the authors also used this in their paper. Hope that clarifies the question :)

**Comment by JSP21** [comment]
Thank you for the clarification :)
